name: Publish

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            version:
                description: "Version to release"
                required: false
                default: "latest"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Get new version
              id: get_version
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.get_version.outputs.version }}
                  name: Release v${{ steps.get_version.outputs.version }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.hiyd_release_pat }}
